# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 21:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('hook_type', models.CharField(choices=[('get', 'Get'), ('post', 'Post'), ('put', 'Put')], max_length=256)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip.Zip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
