# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionwebhook',
            name='title',
            field=models.CharField(default='Webhook Action', max_length=200),
        ),
    ]
